//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETTU_Gadgets_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DragonModelsContainer : DbContext
    {
        public DragonModelsContainer()
            : base("name=DragonModelsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Boat> BoatSet { get; set; }
        public DbSet<Race> RaceSet { get; set; }
        public DbSet<Person> PersonSet { get; set; }
        public DbSet<RaceResult> RaceResultSet { get; set; }
        public DbSet<RaceImage> RaceImageSet { get; set; }
        public DbSet<RaceSchema> RaceSchemaSet { get; set; }
    }
}
