//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETTU_Gadgets_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public Race()
        {
            this.RaceResult = new HashSet<RaceResult>();
            this.Boats = new HashSet<Boat>();
        }
    
        public int Id { get; set; }
        public int PoolId { get; set; }
    
        public virtual ICollection<RaceResult> RaceResult { get; set; }
        public virtual Pool Pool { get; set; }
        public virtual ICollection<Boat> Boats { get; set; }
    }
}
