//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETTU_Gadgets_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceImage
    {
        public RaceImage()
        {
            this.Boats = new HashSet<Boat>();
            this.Persons = new HashSet<Person>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Boat> Boats { get; set; }
        public virtual ICollection<Person> Persons { get; set; }
    }
}
